name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Install dependencies for all workspaces
      - name: Install Dependencies
        run: yarn install
      
      # Build the frontend workspace (assumes a "build" script in /front)
      - name: Build Frontend
        run: yarn workspace front build
      
      # Optionally build the backend if you have a build step (or skip if not needed)
      - name: Build Backend
        run: yarn workspace back build || echo "No backend build script"

  deploy-frontend:
    name: Deploy Frontend to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Build Frontend
        run: yarn workspace front build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/build

  deploy-backend:
    name: Deploy Backend to Heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Build Backend
        run: yarn workspace back build || echo "No backend build script"
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "your-heroku-app-name"  # Replace with your Heroku app name
          heroku_email: "your-email@example.com"   # Replace with your Heroku account email
